### ISSUE TITLE
paymentView 구현 완료

### ISSUE THREAD

**Issue by kex8977** [suri0000/OrderSo10Jo#16]
## 🛠️ 작업 목적
paymentView 및 paymentStackView 구현

## 📝 To-do
- [x] 각각의 xib파일과 swift파일 연결하고, MainView에도 연결해주기
- [x] 주문의 내역이 추가, 변경, 삭제되는 경우마다 합계 업데이트
- [x] 주문 취소버튼 누를 시 전체 주문 목록 초기화

### 참고 사항
얼마나 많고 많은 에러들을 넘었나.... ㅠㅠ
