### ISSUE TITLE
타이틀 뷰 만들기

### ISSUE THREAD

**Issue by qkwmapel** [suri0000/OrderSo10Jo#2]
## 🛠️ 작업 목적

타이틀 뷰 만들기

## 📝 To-do
- [x] 타이틀 만들기
- [x] 검색 버튼 만들기
- [x] 카테고리 세그먼트 만들기
- [ ] 버튼 클릭시 검색창 구현
