### ISSUE TITLE
총 주문 내역 & 취소 결제 버튼

### ISSUE THREAD

**Issue by kex8977** [suri0000/OrderSo10Jo#4]
## 🛠️ 작업 목적
주문 내역 합산 내용 화면표시
결제 하기
주문 취소하기

## 📝 To-do
- [x] 주문 내역 합산내용 출력하기
- [x] 결제 버튼 
- [x] 취소 버튼
- [x] 결제 버튼 누를 시 결제완료 알럿 창 구현
- [x] 취소 버튼 누를 시 정말 취소할 것인지 묻는 알럿 창 구현

**Comment by kex8977** [comment]
1
